const SampleData = {
  TestCaseFormid: [
    {
      type: "Pre Conditions",
      id: "0",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["The Shawshank Redemption", "The Godfather", "The Matrix"],
      description: [
        "Descrption-1",
        "Descrption-2",
        "Descrption-3",
        "Descrption-4",
      ],
      desiredValue: [
        "DesiredValue-1",
        "DesiredValue-2",
        "DesiredValue-3",
        "DesiredValue-4",
      ],
      extensions: [
        "Extensions-1",
        "Extensions-2",
        "Extensions-3",
        "Extensions-4",
      ],
      comments: ["Comment-1", "Comment-2", "Comment-3", "Comment-4"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "0",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: [
        "The Dark Knight",
        "The Godfather: Part II",
        "The Redemption",
      ],
      description: [
        "Descrption-11",
        "Descrption-22",
        "Descrption-33",
        "Descrption-44",
      ],
      desiredValue: [
        "DesiredValue-11",
        "DesiredValue-22",
        "DesiredValue-33",
        "DesiredValue-44",
      ],
      extensions: [
        "Extensions-11",
        "Extensions-22",
        "Extensions-33",
        "Extensions-44",
      ],
      comments: ["Comment-11", "Comment-22", "Comment-33", "Comment-44"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "0",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["The Shawshank Redemption", "The Godfather", "The Matrix"],
      description: [
        "Descrption-1",
        "Descrption-2",
        "Descrption-3",
        "Descrption-4",
      ],
      desiredValue: [
        "DesiredValue-1",
        "DesiredValue-2",
        "DesiredValue-3",
        "DesiredValue-4",
      ],
      extensions: [
        "Extensions-1",
        "Extensions-2",
        "Extensions-3",
        "Extensions-4",
      ],
      comments: ["Comment-1", "Comment-2", "Comment-3", "Comment-4"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "0",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["12 Angry Men", "Schindler's List", "Pulp Fiction"],
      description: [
        "Descrption-21",
        "Descrption-22",
        "Descrption-23",
        "Descrption-24",
      ],
      desiredValue: [
        "DesiredValue-21",
        "DesiredValue-22",
        "DesiredValue-23",
        "DesiredValue-24",
      ],
      extensions: [
        "Extensions-21",
        "Extensions-22",
        "Extensions-23",
        "Extensions-24",
      ],
      comments: ["Comment-21", "Comment-22", "Comment-23", "Comment-24"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "03",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["The Lord of the Rings: The Return of the King", "Fight Club", "The Matrix"],
      description: [
        "Descrption-31",
        "Descrption-32",
        "Descrption-33",
        "Descrption-34",
      ],
      desiredValue: [
        "DesiredValue-31",
        "DesiredValue-32",
        "DesiredValue-33",
        "DesiredValue-34",
      ],
      extensions: [
        "Extensions-31",
        "Extensions-32",
        "Extensions-33",
        "Extensions-34",
      ],
      comments: ["Comment-31", "Comment-32", "Comment-33", "Comment-34"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "04",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["Forrest Gump", "The Godfather", "The Matrix"],
      description: [
        "Descrption-41",
        "Descrption-42",
        "Descrption-43",
        "Descrption-44",
      ],
      desiredValue: [
        "DesiredValue-41",
        "DesiredValue-42",
        "DesiredValue-43",
        "DesiredValue-44",
      ],
      extensions: [
        "Extensions-41",
        "Extensions-42",
        "Extensions-43",
        "Extensions-44",
      ],
      comments: ["Comment-41", "Comment-42", "Comment-43", "Comment-44"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "05",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["Inception", "The Matrix", "The Godfather"],
      description: [
        "Descrption-51",
        "Descrption-52",
        "Descrption-53",
        "Descrption-54",
      ],
      desiredValue: [
        "DesiredValue-51",
        "DesiredValue-52",
        "DesiredValue-53",
        "DesiredValue-54",
      ],
      extensions: [
        "Extensions-51",
        "Extensions-52",
        "Extensions-53",
        "Extensions-54",
      ],
      comments: ["Comment-51", "Comment-52", "Comment-53", "Comment-54"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "6",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["Goodfellas", "Inception", "Star Wars"],
      description: [
        "Descrption-61",
        "Descrption-62",
        "Descrption-63",
        "Descrption-64",
      ],
      desiredValue: [
        "DesiredValue-61",
        "DesiredValue-62",
        "DesiredValue-63",
        "DesiredValue-64",
      ],
      extensions: [
        "Extensions-61",
        "Extensions-62",
        "Extensions-63",
        "Extensions-64",
      ],
      comments: ["Comment-61", "Comment-62", "Comment-63", "Comment-64"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "7",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["The Shawshank Redemption", "Forrest Gump", "The Lord of the Rings", "Goodfellas"],
      description: [
        "Descrption-71",
        "Descrption-72",
        "Descrption-73",
        "Descrption-74",
      ],
      desiredValue: [
        "DesiredValue-71",
        "DesiredValue-72",
        "DesiredValue-73",
        "DesiredValue-74",
      ],
      extensions: [
        "Extensions-71",
        "Extensions-72",
        "Extensions-73",
        "Extensions-74",
      ],
      comments: ["Comment-71", "Comment-72", "Comment-73", "Comment-74"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
    {
      type: "Pre Conditions",
      id: "8",
      idHead: "#",
      action: "Pre Conditions",
      serviceType: ["Pulp Fiction","The Shawshank Redemption", "The Godfather", "The Matrix"],
      description: [
        "Descrption-81",
        "Descrption-82",
        "Descrption-83",
        "Descrption-84",
      ],
      desiredValue: [
        "DesiredValue-81",
        "DesiredValue-82",
        "DesiredValue-83",
        "DesiredValue-84",
      ],
      extensions: [
        "Extensions-81",
        "Extensions-82",
        "Extensions-83",
        "Extensions-84",
      ],
      comments: ["Comment-81", "Comment-82", "Comment-83", "Comment-84"],
      stepData: "#",
      refId: "#",
      extensionsHideInfomation: [],
      extnId: [1, 2, 3],
    },
  ],
};

export default SampleData;
